kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang
    commands: 
      - make install-drone
      - make test-drone
    
  - name: coverage
    failure: ignore
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN

  - name: build
    image: golang
    commands:
      - make build

  - name: deploy
    image: nytimes/drone-gae
    action: deploy
    project: financial-calculator-dev
    dir: cmd/server
    app_file: app.yaml
    max_versions: 2
  #  environment:
  #    - GOPATH=/drone
    when:
      event: push
      branch: [master]