// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package financial

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mode int32

const (
	Mode_INVESTMENTS Mode = 0
	Mode_DEBT        Mode = 1
)

var Mode_name = map[int32]string{
	0: "INVESTMENTS",
	1: "DEBT",
}

var Mode_value = map[string]int32{
	"INVESTMENTS": 0,
	"DEBT":        1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Account struct {
	// Not all accounts accrue interest at the same rate. Some may accrue interest once per year, once per month, etc. Since we use periods we need to know how many periods before interest is calculated. So, on a bi-weekly paycheck you might choose to view interest every 2 periods.
	AddInterestEveryNPeriods int64 `protobuf:"varint,1,opt,name=AddInterestEveryNPeriods,proto3" json:"AddInterestEveryNPeriods,omitempty"`
	// The Balance of the account. 45.05
	Balance float64 `protobuf:"fixed64,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Id      int64   `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
	// The interest rate of hte account. %5.5 is 0.055.
	InterestRate         float64  `protobuf:"fixed64,4,opt,name=InterestRate,proto3" json:"InterestRate,omitempty"`
	Mode                 Mode     `protobuf:"varint,5,opt,name=Mode,proto3,enum=financialplanningcalculator.Mode" json:"Mode,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	UserId               int64    `protobuf:"varint,7,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddInterestEveryNPeriods() int64 {
	if m != nil {
		return m.AddInterestEveryNPeriods
	}
	return 0
}

func (m *Account) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetInterestRate() float64 {
	if m != nil {
		return m.InterestRate
	}
	return 0
}

func (m *Account) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_INVESTMENTS
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CalculateResponse struct {
	Periods              *Period  `protobuf:"bytes,1,opt,name=Periods,proto3" json:"Periods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateResponse) Reset()         { *m = CalculateResponse{} }
func (m *CalculateResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateResponse) ProtoMessage()    {}
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *CalculateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateResponse.Unmarshal(m, b)
}
func (m *CalculateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateResponse.Marshal(b, m, deterministic)
}
func (m *CalculateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateResponse.Merge(m, src)
}
func (m *CalculateResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateResponse.Size(m)
}
func (m *CalculateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateResponse proto.InternalMessageInfo

func (m *CalculateResponse) GetPeriods() *Period {
	if m != nil {
		return m.Periods
	}
	return nil
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAccountsData struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsData) Reset()         { *m = GetAccountsData{} }
func (m *GetAccountsData) String() string { return proto.CompactTextString(m) }
func (*GetAccountsData) ProtoMessage()    {}
func (*GetAccountsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetAccountsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsData.Unmarshal(m, b)
}
func (m *GetAccountsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsData.Marshal(b, m, deterministic)
}
func (m *GetAccountsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsData.Merge(m, src)
}
func (m *GetAccountsData) XXX_Size() int {
	return xxx_messageInfo_GetAccountsData.Size(m)
}
func (m *GetAccountsData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsData.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsData proto.InternalMessageInfo

func (m *GetAccountsData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetAccountsRequest struct {
	Data                 *GetAccountsData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(m, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

func (m *GetAccountsRequest) GetData() *GetAccountsData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(m, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetUserData struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserData) Reset()         { *m = GetUserData{} }
func (m *GetUserData) String() string { return proto.CompactTextString(m) }
func (*GetUserData) ProtoMessage()    {}
func (*GetUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *GetUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserData.Unmarshal(m, b)
}
func (m *GetUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserData.Marshal(b, m, deterministic)
}
func (m *GetUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserData.Merge(m, src)
}
func (m *GetUserData) XXX_Size() int {
	return xxx_messageInfo_GetUserData.Size(m)
}
func (m *GetUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserData.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserData proto.InternalMessageInfo

func (m *GetUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	Data                 *GetUserData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetData() *GetUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Period struct {
	Accounts             *Account `protobuf:"bytes,1,opt,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (m *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(m, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetAccounts() *Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type PostAccountRequest struct {
	Data                 *Account `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountRequest) Reset()         { *m = PostAccountRequest{} }
func (m *PostAccountRequest) String() string { return proto.CompactTextString(m) }
func (*PostAccountRequest) ProtoMessage()    {}
func (*PostAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *PostAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountRequest.Unmarshal(m, b)
}
func (m *PostAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountRequest.Marshal(b, m, deterministic)
}
func (m *PostAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountRequest.Merge(m, src)
}
func (m *PostAccountRequest) XXX_Size() int {
	return xxx_messageInfo_PostAccountRequest.Size(m)
}
func (m *PostAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountRequest proto.InternalMessageInfo

func (m *PostAccountRequest) GetData() *Account {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostAccountResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountResponse) Reset()         { *m = PostAccountResponse{} }
func (m *PostAccountResponse) String() string { return proto.CompactTextString(m) }
func (*PostAccountResponse) ProtoMessage()    {}
func (*PostAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *PostAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountResponse.Unmarshal(m, b)
}
func (m *PostAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountResponse.Marshal(b, m, deterministic)
}
func (m *PostAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountResponse.Merge(m, src)
}
func (m *PostAccountResponse) XXX_Size() int {
	return xxx_messageInfo_PostAccountResponse.Size(m)
}
func (m *PostAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountResponse proto.InternalMessageInfo

func (m *PostAccountResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PostUserData struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUserData) Reset()         { *m = PostUserData{} }
func (m *PostUserData) String() string { return proto.CompactTextString(m) }
func (*PostUserData) ProtoMessage()    {}
func (*PostUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *PostUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserData.Unmarshal(m, b)
}
func (m *PostUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserData.Marshal(b, m, deterministic)
}
func (m *PostUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserData.Merge(m, src)
}
func (m *PostUserData) XXX_Size() int {
	return xxx_messageInfo_PostUserData.Size(m)
}
func (m *PostUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserData.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserData proto.InternalMessageInfo

func (m *PostUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type PostUserRequest struct {
	Data                 *PostUserData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostUserRequest) Reset()         { *m = PostUserRequest{} }
func (m *PostUserRequest) String() string { return proto.CompactTextString(m) }
func (*PostUserRequest) ProtoMessage()    {}
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *PostUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserRequest.Unmarshal(m, b)
}
func (m *PostUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserRequest.Marshal(b, m, deterministic)
}
func (m *PostUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserRequest.Merge(m, src)
}
func (m *PostUserRequest) XXX_Size() int {
	return xxx_messageInfo_PostUserRequest.Size(m)
}
func (m *PostUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserRequest proto.InternalMessageInfo

func (m *PostUserRequest) GetData() *PostUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserResponse struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("financialplanningcalculator.Mode", Mode_name, Mode_value)
	proto.RegisterType((*Account)(nil), "financialplanningcalculator.Account")
	proto.RegisterType((*CalculateResponse)(nil), "financialplanningcalculator.CalculateResponse")
	proto.RegisterType((*Error)(nil), "financialplanningcalculator.Error")
	proto.RegisterType((*GetAccountsData)(nil), "financialplanningcalculator.GetAccountsData")
	proto.RegisterType((*GetAccountsRequest)(nil), "financialplanningcalculator.GetAccountsRequest")
	proto.RegisterType((*GetAccountsResponse)(nil), "financialplanningcalculator.GetAccountsResponse")
	proto.RegisterType((*GetUserData)(nil), "financialplanningcalculator.GetUserData")
	proto.RegisterType((*GetUserRequest)(nil), "financialplanningcalculator.GetUserRequest")
	proto.RegisterType((*Period)(nil), "financialplanningcalculator.Period")
	proto.RegisterType((*PostAccountRequest)(nil), "financialplanningcalculator.PostAccountRequest")
	proto.RegisterType((*PostAccountResponse)(nil), "financialplanningcalculator.PostAccountResponse")
	proto.RegisterType((*PostUserData)(nil), "financialplanningcalculator.PostUserData")
	proto.RegisterType((*PostUserRequest)(nil), "financialplanningcalculator.PostUserRequest")
	proto.RegisterType((*UserResponse)(nil), "financialplanningcalculator.UserResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xe1, 0x4b, 0xdb, 0x40,
	0x1c, 0xed, 0xd5, 0xd8, 0xea, 0xaf, 0x4e, 0xdd, 0x39, 0x24, 0xd4, 0x2f, 0xed, 0xe9, 0x20, 0x6e,
	0x92, 0x8e, 0x6e, 0x83, 0x31, 0x26, 0x68, 0x35, 0x93, 0x0e, 0x1a, 0xca, 0xb5, 0x73, 0x30, 0xf6,
	0xe5, 0x4c, 0xce, 0x12, 0x48, 0x93, 0x2e, 0xb9, 0x0a, 0xfe, 0x63, 0xfb, 0xd3, 0xf6, 0x79, 0x24,
	0xb9, 0x2b, 0x89, 0xba, 0xb4, 0xf8, 0xad, 0x97, 0xbe, 0xdf, 0xbb, 0xf7, 0x1e, 0xef, 0x7e, 0xf0,
	0x22, 0xe6, 0xd1, 0x9d, 0xe7, 0x70, 0x73, 0x16, 0x85, 0x22, 0xc4, 0x07, 0xb7, 0x5e, 0xc0, 0x02,
	0xc7, 0x63, 0xfe, 0xcc, 0x67, 0x41, 0xe0, 0x05, 0x13, 0x87, 0xf9, 0xce, 0xdc, 0x67, 0x22, 0x8c,
	0x9a, 0x07, 0x93, 0x30, 0x9c, 0xf8, 0xbc, 0x93, 0x42, 0x6f, 0xe6, 0xb7, 0x1d, 0x3e, 0x9d, 0x89,
	0xfb, 0x6c, 0x92, 0xfc, 0x45, 0x50, 0x3f, 0x77, 0x9c, 0x70, 0x1e, 0x08, 0xfc, 0x19, 0xf4, 0x73,
	0xd7, 0xed, 0x07, 0x82, 0x47, 0x3c, 0x16, 0xd6, 0x1d, 0x8f, 0xee, 0xed, 0x21, 0x8f, 0xbc, 0xd0,
	0x8d, 0x75, 0xd4, 0x42, 0xc6, 0x1a, 0xfd, 0xef, 0xff, 0x58, 0x87, 0x7a, 0x8f, 0xf9, 0x2c, 0x70,
	0xb8, 0x5e, 0x6d, 0x21, 0x03, 0x51, 0x75, 0xc4, 0xdb, 0x50, 0xed, 0xbb, 0xfa, 0x5a, 0x3a, 0x5f,
	0xed, 0xbb, 0x98, 0xc0, 0x96, 0xa2, 0xa0, 0x4c, 0x70, 0x5d, 0x4b, 0xe1, 0x85, 0x6f, 0xf8, 0x23,
	0x68, 0x83, 0xd0, 0xe5, 0xfa, 0x7a, 0x0b, 0x19, 0xdb, 0xdd, 0xb6, 0x59, 0x62, 0xcf, 0x4c, 0x80,
	0x34, 0x85, 0x63, 0x0c, 0x9a, 0xcd, 0xa6, 0x5c, 0xaf, 0xb5, 0x90, 0xb1, 0x49, 0xd3, 0xdf, 0x78,
	0x1f, 0x6a, 0xdf, 0x63, 0x1e, 0xf5, 0x5d, 0xbd, 0x9e, 0x4a, 0x90, 0x27, 0x42, 0xe1, 0xe5, 0x85,
	0x24, 0xe1, 0x94, 0xc7, 0xb3, 0x30, 0x88, 0x39, 0x3e, 0x85, 0x7a, 0xde, 0x70, 0xa3, 0x7b, 0x58,
	0x7a, 0x75, 0x86, 0xa5, 0x6a, 0x86, 0xb4, 0x61, 0xdd, 0x8a, 0xa2, 0x30, 0x4a, 0xd2, 0x18, 0xf0,
	0x38, 0x66, 0x13, 0x9e, 0xf2, 0x6c, 0x52, 0x75, 0x24, 0xc7, 0xb0, 0x73, 0xc5, 0x85, 0x4c, 0x3c,
	0xbe, 0x64, 0x82, 0xe5, 0x14, 0xa2, 0x82, 0xc2, 0x6b, 0xc0, 0x39, 0x28, 0xe5, 0xbf, 0xe7, 0x3c,
	0x16, 0xf8, 0x0c, 0x34, 0x97, 0x09, 0x26, 0xf5, 0x9d, 0x94, 0xea, 0x7b, 0x70, 0x13, 0x4d, 0x27,
	0xc9, 0x0f, 0xd8, 0x2b, 0xf0, 0x4a, 0xef, 0x67, 0xb0, 0xa1, 0xbe, 0xe9, 0xa8, 0xb5, 0x66, 0x34,
	0xba, 0x47, 0xa5, 0xe4, 0x12, 0x4c, 0x17, 0x53, 0xe4, 0x10, 0x1a, 0x57, 0x5c, 0x24, 0xea, 0x53,
	0x5f, 0xaf, 0x60, 0xdd, 0x9a, 0x32, 0xcf, 0x97, 0x11, 0x64, 0x07, 0x62, 0xc3, 0xb6, 0x04, 0x29,
	0x47, 0x5f, 0x0a, 0x8e, 0x8c, 0x65, 0x8e, 0x14, 0xbf, 0x74, 0xf3, 0x0d, 0x6a, 0x59, 0xfc, 0x0f,
	0x0c, 0xa0, 0x67, 0x18, 0xb0, 0x01, 0x0f, 0xc3, 0x58, 0x45, 0xa3, 0xf4, 0x7d, 0x2a, 0xe8, 0x5b,
	0x8d, 0x33, 0xd3, 0xf6, 0x1a, 0xf6, 0x0a, 0x7c, 0x32, 0xe9, 0xec, 0x45, 0x20, 0xf5, 0x22, 0xc8,
	0x11, 0x6c, 0x25, 0xb0, 0x25, 0xc1, 0x0d, 0x61, 0x47, 0xa1, 0x94, 0xb2, 0xd3, 0x82, 0xb2, 0xe3,
	0xf2, 0xae, 0xe6, 0x6e, 0x90, 0xf2, 0x3e, 0xc0, 0x56, 0xc6, 0x26, 0x75, 0x3d, 0x79, 0xaf, 0x54,
	0x5b, 0x55, 0x6a, 0xdf, 0xb4, 0xb3, 0xb7, 0x89, 0x77, 0xa0, 0xd1, 0xb7, 0xaf, 0xad, 0xd1, 0x78,
	0x60, 0xd9, 0xe3, 0xd1, 0x6e, 0x05, 0x6f, 0x80, 0x76, 0x69, 0xf5, 0xc6, 0xbb, 0xa8, 0xfb, 0x47,
	0x03, 0xf2, 0x55, 0x69, 0x19, 0x4a, 0x2d, 0x17, 0x0b, 0x2d, 0xa3, 0x6c, 0x77, 0xe1, 0x28, 0xed,
	0x8b, 0x4a, 0x1f, 0x77, 0x56, 0xed, 0xb2, 0xb4, 0xdf, 0x7c, 0xb7, 0xfa, 0x40, 0xe6, 0x90, 0x54,
	0xb0, 0x03, 0x75, 0xd9, 0x21, 0xfc, 0x76, 0x95, 0xa6, 0xa9, 0xbb, 0xca, 0xc3, 0xcd, 0xc7, 0x48,
	0x2a, 0xf8, 0x17, 0xec, 0xca, 0xf1, 0xc5, 0x8a, 0xc1, 0xfb, 0x66, 0xb6, 0x86, 0x4d, 0xb5, 0x86,
	0x4d, 0x2b, 0x59, 0xc3, 0x4d, 0xb3, 0x94, 0xf8, 0xd1, 0x8a, 0x22, 0x95, 0x24, 0xb6, 0x5c, 0xab,
	0x96, 0xc4, 0xf6, 0xb8, 0xcf, 0x4b, 0x62, 0x7b, 0xa2, 0xb0, 0xa4, 0x82, 0x39, 0x6c, 0xa8, 0x02,
	0xe1, 0x93, 0x95, 0x7a, 0xf6, 0x9c, 0xe0, 0x7a, 0x8d, 0x9f, 0x9b, 0x0b, 0xf4, 0x4d, 0x2d, 0x4d,
	0xea, 0xfd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x78, 0xbd, 0x44, 0xec, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FinancialPlanningCalculatorServiceClient is the client API for FinancialPlanningCalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FinancialPlanningCalculatorServiceClient interface {
	// Get accounts
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error)
	// Get a new user.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	// Calculate for the current user.
	GetUserCalculate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CalculateResponse, error)
	// Create an account.
	PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error)
	// Create a new user.
	PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type financialPlanningCalculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewFinancialPlanningCalculatorServiceClient(cc *grpc.ClientConn) FinancialPlanningCalculatorServiceClient {
	return &financialPlanningCalculatorServiceClient{cc}
}

func (c *financialPlanningCalculatorServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error) {
	out := new(GetAccountsResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) GetUserCalculate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUserCalculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error) {
	out := new(PostAccountResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/PostAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/PostUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialPlanningCalculatorServiceServer is the server API for FinancialPlanningCalculatorService service.
type FinancialPlanningCalculatorServiceServer interface {
	// Get accounts
	GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error)
	// Get a new user.
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	// Calculate for the current user.
	GetUserCalculate(context.Context, *empty.Empty) (*CalculateResponse, error)
	// Create an account.
	PostAccount(context.Context, *PostAccountRequest) (*PostAccountResponse, error)
	// Create a new user.
	PostUser(context.Context, *PostUserRequest) (*UserResponse, error)
}

// UnimplementedFinancialPlanningCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFinancialPlanningCalculatorServiceServer struct {
}

func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetAccounts(ctx context.Context, req *GetAccountsRequest) (*GetAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetUserCalculate(ctx context.Context, req *empty.Empty) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCalculate not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) PostAccount(ctx context.Context, req *PostAccountRequest) (*PostAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAccount not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) PostUser(ctx context.Context, req *PostUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUser not implemented")
}

func RegisterFinancialPlanningCalculatorServiceServer(s *grpc.Server, srv FinancialPlanningCalculatorServiceServer) {
	s.RegisterService(&_FinancialPlanningCalculatorService_serviceDesc, srv)
}

func _FinancialPlanningCalculatorService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_GetUserCalculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUserCalculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUserCalculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUserCalculate(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_PostAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).PostAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/PostAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).PostAccount(ctx, req.(*PostAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_PostUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).PostUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/PostUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).PostUser(ctx, req.(*PostUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FinancialPlanningCalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "financialplanningcalculator.FinancialPlanningCalculatorService",
	HandlerType: (*FinancialPlanningCalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccounts",
			Handler:    _FinancialPlanningCalculatorService_GetAccounts_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _FinancialPlanningCalculatorService_GetUser_Handler,
		},
		{
			MethodName: "GetUserCalculate",
			Handler:    _FinancialPlanningCalculatorService_GetUserCalculate_Handler,
		},
		{
			MethodName: "PostAccount",
			Handler:    _FinancialPlanningCalculatorService_PostAccount_Handler,
		},
		{
			MethodName: "PostUser",
			Handler:    _FinancialPlanningCalculatorService_PostUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
