// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package financial

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Mode int32

const (
	Mode_INVESTMENTS Mode = 0
	Mode_DEBT        Mode = 1
)

var Mode_name = map[int32]string{
	0: "INVESTMENTS",
	1: "DEBT",
}

var Mode_value = map[string]int32{
	"INVESTMENTS": 0,
	"DEBT":        1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}

func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

type Account struct {
	// Not all accounts accrue interest at the same rate. Some may accrue interest once per year, once per month, etc. Since we use periods we need to know how many periods before interest is calculated. So, on a bi-weekly paycheck you might choose to view interest every 2 periods.
	AddInterestEveryNPeriods int64 `protobuf:"varint,1,opt,name=AddInterestEveryNPeriods,proto3" json:"AddInterestEveryNPeriods,omitempty"`
	// The Balance of the account. 45.05
	Balance float64 `protobuf:"fixed64,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Id      int64   `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
	// The interest rate of hte account. %5.5 is 0.055.
	InterestRate         float64  `protobuf:"fixed64,4,opt,name=InterestRate,proto3" json:"InterestRate,omitempty"`
	Mode                 Mode     `protobuf:"varint,5,opt,name=Mode,proto3,enum=financialplanningcalculator.Mode" json:"Mode,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=Name,proto3" json:"Name,omitempty"`
	UserId               int64    `protobuf:"varint,7,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddInterestEveryNPeriods() int64 {
	if m != nil {
		return m.AddInterestEveryNPeriods
	}
	return 0
}

func (m *Account) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Account) GetInterestRate() float64 {
	if m != nil {
		return m.InterestRate
	}
	return 0
}

func (m *Account) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_INVESTMENTS
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Contribution struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contribution) Reset()         { *m = Contribution{} }
func (m *Contribution) String() string { return proto.CompactTextString(m) }
func (*Contribution) ProtoMessage()    {}
func (*Contribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *Contribution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contribution.Unmarshal(m, b)
}
func (m *Contribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contribution.Marshal(b, m, deterministic)
}
func (m *Contribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contribution.Merge(m, src)
}
func (m *Contribution) XXX_Size() int {
	return xxx_messageInfo_Contribution.Size(m)
}
func (m *Contribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Contribution.DiscardUnknown(m)
}

var xxx_messageInfo_Contribution proto.InternalMessageInfo

func (m *Contribution) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Contribution) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Contribution) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetAccountsData struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsData) Reset()         { *m = GetAccountsData{} }
func (m *GetAccountsData) String() string { return proto.CompactTextString(m) }
func (*GetAccountsData) ProtoMessage()    {}
func (*GetAccountsData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *GetAccountsData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsData.Unmarshal(m, b)
}
func (m *GetAccountsData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsData.Marshal(b, m, deterministic)
}
func (m *GetAccountsData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsData.Merge(m, src)
}
func (m *GetAccountsData) XXX_Size() int {
	return xxx_messageInfo_GetAccountsData.Size(m)
}
func (m *GetAccountsData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsData.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsData proto.InternalMessageInfo

func (m *GetAccountsData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetAccountsRequest struct {
	Data                 *GetAccountsData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{4}
}

func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(m, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

func (m *GetAccountsRequest) GetData() *GetAccountsData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{5}
}

func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(m, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type GetCalculateData struct {
	Periods              int64    `protobuf:"varint,1,opt,name=Periods,proto3" json:"Periods,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCalculateData) Reset()         { *m = GetCalculateData{} }
func (m *GetCalculateData) String() string { return proto.CompactTextString(m) }
func (*GetCalculateData) ProtoMessage()    {}
func (*GetCalculateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{6}
}

func (m *GetCalculateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalculateData.Unmarshal(m, b)
}
func (m *GetCalculateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalculateData.Marshal(b, m, deterministic)
}
func (m *GetCalculateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalculateData.Merge(m, src)
}
func (m *GetCalculateData) XXX_Size() int {
	return xxx_messageInfo_GetCalculateData.Size(m)
}
func (m *GetCalculateData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalculateData.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalculateData proto.InternalMessageInfo

func (m *GetCalculateData) GetPeriods() int64 {
	if m != nil {
		return m.Periods
	}
	return 0
}

func (m *GetCalculateData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetCalculateRequest struct {
	Data                 *GetCalculateData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetCalculateRequest) Reset()         { *m = GetCalculateRequest{} }
func (m *GetCalculateRequest) String() string { return proto.CompactTextString(m) }
func (*GetCalculateRequest) ProtoMessage()    {}
func (*GetCalculateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{7}
}

func (m *GetCalculateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalculateRequest.Unmarshal(m, b)
}
func (m *GetCalculateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalculateRequest.Marshal(b, m, deterministic)
}
func (m *GetCalculateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalculateRequest.Merge(m, src)
}
func (m *GetCalculateRequest) XXX_Size() int {
	return xxx_messageInfo_GetCalculateRequest.Size(m)
}
func (m *GetCalculateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalculateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalculateRequest proto.InternalMessageInfo

func (m *GetCalculateRequest) GetData() *GetCalculateData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetCalculateResponse struct {
	Periods              []*Period `protobuf:"bytes,1,rep,name=Periods,proto3" json:"Periods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetCalculateResponse) Reset()         { *m = GetCalculateResponse{} }
func (m *GetCalculateResponse) String() string { return proto.CompactTextString(m) }
func (*GetCalculateResponse) ProtoMessage()    {}
func (*GetCalculateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{8}
}

func (m *GetCalculateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCalculateResponse.Unmarshal(m, b)
}
func (m *GetCalculateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCalculateResponse.Marshal(b, m, deterministic)
}
func (m *GetCalculateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCalculateResponse.Merge(m, src)
}
func (m *GetCalculateResponse) XXX_Size() int {
	return xxx_messageInfo_GetCalculateResponse.Size(m)
}
func (m *GetCalculateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCalculateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCalculateResponse proto.InternalMessageInfo

func (m *GetCalculateResponse) GetPeriods() []*Period {
	if m != nil {
		return m.Periods
	}
	return nil
}

type GetContributionData struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=AccountId,proto3" json:"AccountId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContributionData) Reset()         { *m = GetContributionData{} }
func (m *GetContributionData) String() string { return proto.CompactTextString(m) }
func (*GetContributionData) ProtoMessage()    {}
func (*GetContributionData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{9}
}

func (m *GetContributionData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContributionData.Unmarshal(m, b)
}
func (m *GetContributionData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContributionData.Marshal(b, m, deterministic)
}
func (m *GetContributionData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContributionData.Merge(m, src)
}
func (m *GetContributionData) XXX_Size() int {
	return xxx_messageInfo_GetContributionData.Size(m)
}
func (m *GetContributionData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContributionData.DiscardUnknown(m)
}

var xxx_messageInfo_GetContributionData proto.InternalMessageInfo

func (m *GetContributionData) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type GetContributionRequest struct {
	Data                 *GetContributionData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetContributionRequest) Reset()         { *m = GetContributionRequest{} }
func (m *GetContributionRequest) String() string { return proto.CompactTextString(m) }
func (*GetContributionRequest) ProtoMessage()    {}
func (*GetContributionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{10}
}

func (m *GetContributionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContributionRequest.Unmarshal(m, b)
}
func (m *GetContributionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContributionRequest.Marshal(b, m, deterministic)
}
func (m *GetContributionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContributionRequest.Merge(m, src)
}
func (m *GetContributionRequest) XXX_Size() int {
	return xxx_messageInfo_GetContributionRequest.Size(m)
}
func (m *GetContributionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContributionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContributionRequest proto.InternalMessageInfo

func (m *GetContributionRequest) GetData() *GetContributionData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetGoalData struct {
	UserId               int64    `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoalData) Reset()         { *m = GetGoalData{} }
func (m *GetGoalData) String() string { return proto.CompactTextString(m) }
func (*GetGoalData) ProtoMessage()    {}
func (*GetGoalData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{11}
}

func (m *GetGoalData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoalData.Unmarshal(m, b)
}
func (m *GetGoalData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoalData.Marshal(b, m, deterministic)
}
func (m *GetGoalData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoalData.Merge(m, src)
}
func (m *GetGoalData) XXX_Size() int {
	return xxx_messageInfo_GetGoalData.Size(m)
}
func (m *GetGoalData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoalData.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoalData proto.InternalMessageInfo

func (m *GetGoalData) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetGoalsRequest struct {
	Data                 *GetGoalData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetGoalsRequest) Reset()         { *m = GetGoalsRequest{} }
func (m *GetGoalsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGoalsRequest) ProtoMessage()    {}
func (*GetGoalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{12}
}

func (m *GetGoalsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoalsRequest.Unmarshal(m, b)
}
func (m *GetGoalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoalsRequest.Marshal(b, m, deterministic)
}
func (m *GetGoalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoalsRequest.Merge(m, src)
}
func (m *GetGoalsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGoalsRequest.Size(m)
}
func (m *GetGoalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoalsRequest proto.InternalMessageInfo

func (m *GetGoalsRequest) GetData() *GetGoalData {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetGoalsResponse struct {
	Goals                []*Goal  `protobuf:"bytes,1,rep,name=Goals,proto3" json:"Goals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoalsResponse) Reset()         { *m = GetGoalsResponse{} }
func (m *GetGoalsResponse) String() string { return proto.CompactTextString(m) }
func (*GetGoalsResponse) ProtoMessage()    {}
func (*GetGoalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{13}
}

func (m *GetGoalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoalsResponse.Unmarshal(m, b)
}
func (m *GetGoalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoalsResponse.Marshal(b, m, deterministic)
}
func (m *GetGoalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoalsResponse.Merge(m, src)
}
func (m *GetGoalsResponse) XXX_Size() int {
	return xxx_messageInfo_GetGoalsResponse.Size(m)
}
func (m *GetGoalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoalsResponse proto.InternalMessageInfo

func (m *GetGoalsResponse) GetGoals() []*Goal {
	if m != nil {
		return m.Goals
	}
	return nil
}

type GetHealthRequest struct {
	Data                 *GetHealthRequest_DataMessage `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetHealthRequest) Reset()         { *m = GetHealthRequest{} }
func (m *GetHealthRequest) String() string { return proto.CompactTextString(m) }
func (*GetHealthRequest) ProtoMessage()    {}
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14}
}

func (m *GetHealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthRequest.Unmarshal(m, b)
}
func (m *GetHealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthRequest.Marshal(b, m, deterministic)
}
func (m *GetHealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthRequest.Merge(m, src)
}
func (m *GetHealthRequest) XXX_Size() int {
	return xxx_messageInfo_GetHealthRequest.Size(m)
}
func (m *GetHealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthRequest proto.InternalMessageInfo

func (m *GetHealthRequest) GetData() *GetHealthRequest_DataMessage {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetHealthRequest_DataMessage struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthRequest_DataMessage) Reset()         { *m = GetHealthRequest_DataMessage{} }
func (m *GetHealthRequest_DataMessage) String() string { return proto.CompactTextString(m) }
func (*GetHealthRequest_DataMessage) ProtoMessage()    {}
func (*GetHealthRequest_DataMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{14, 0}
}

func (m *GetHealthRequest_DataMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthRequest_DataMessage.Unmarshal(m, b)
}
func (m *GetHealthRequest_DataMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthRequest_DataMessage.Marshal(b, m, deterministic)
}
func (m *GetHealthRequest_DataMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthRequest_DataMessage.Merge(m, src)
}
func (m *GetHealthRequest_DataMessage) XXX_Size() int {
	return xxx_messageInfo_GetHealthRequest_DataMessage.Size(m)
}
func (m *GetHealthRequest_DataMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthRequest_DataMessage.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthRequest_DataMessage proto.InternalMessageInfo

type GetHealthResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHealthResponse) Reset()         { *m = GetHealthResponse{} }
func (m *GetHealthResponse) String() string { return proto.CompactTextString(m) }
func (*GetHealthResponse) ProtoMessage()    {}
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{15}
}

func (m *GetHealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHealthResponse.Unmarshal(m, b)
}
func (m *GetHealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHealthResponse.Marshal(b, m, deterministic)
}
func (m *GetHealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHealthResponse.Merge(m, src)
}
func (m *GetHealthResponse) XXX_Size() int {
	return xxx_messageInfo_GetHealthResponse.Size(m)
}
func (m *GetHealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHealthResponse proto.InternalMessageInfo

func (m *GetHealthResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetUserData struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserData) Reset()         { *m = GetUserData{} }
func (m *GetUserData) String() string { return proto.CompactTextString(m) }
func (*GetUserData) ProtoMessage()    {}
func (*GetUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{16}
}

func (m *GetUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserData.Unmarshal(m, b)
}
func (m *GetUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserData.Marshal(b, m, deterministic)
}
func (m *GetUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserData.Merge(m, src)
}
func (m *GetUserData) XXX_Size() int {
	return xxx_messageInfo_GetUserData.Size(m)
}
func (m *GetUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserData.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserData proto.InternalMessageInfo

func (m *GetUserData) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	Data                 *GetUserData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{17}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetData() *GetUserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type Goal struct {
	AccountIds           []int64  `protobuf:"varint,1,rep,packed,name=AccountIds,proto3" json:"AccountIds,omitempty"`
	Balance              float64  `protobuf:"fixed64,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
	Id                   int64    `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	UserId               int64    `protobuf:"varint,5,opt,name=UserId,proto3" json:"UserId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Goal) Reset()         { *m = Goal{} }
func (m *Goal) String() string { return proto.CompactTextString(m) }
func (*Goal) ProtoMessage()    {}
func (*Goal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{18}
}

func (m *Goal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goal.Unmarshal(m, b)
}
func (m *Goal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goal.Marshal(b, m, deterministic)
}
func (m *Goal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goal.Merge(m, src)
}
func (m *Goal) XXX_Size() int {
	return xxx_messageInfo_Goal.Size(m)
}
func (m *Goal) XXX_DiscardUnknown() {
	xxx_messageInfo_Goal.DiscardUnknown(m)
}

var xxx_messageInfo_Goal proto.InternalMessageInfo

func (m *Goal) GetAccountIds() []int64 {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

func (m *Goal) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Goal) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Goal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Goal) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type Period struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	Goals                []*Goal    `protobuf:"bytes,2,rep,name=Goals,proto3" json:"Goals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{19}
}

func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (m *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(m, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *Period) GetGoals() []*Goal {
	if m != nil {
		return m.Goals
	}
	return nil
}

type PostAccountRequest struct {
	Data                 *Account `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountRequest) Reset()         { *m = PostAccountRequest{} }
func (m *PostAccountRequest) String() string { return proto.CompactTextString(m) }
func (*PostAccountRequest) ProtoMessage()    {}
func (*PostAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{20}
}

func (m *PostAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountRequest.Unmarshal(m, b)
}
func (m *PostAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountRequest.Marshal(b, m, deterministic)
}
func (m *PostAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountRequest.Merge(m, src)
}
func (m *PostAccountRequest) XXX_Size() int {
	return xxx_messageInfo_PostAccountRequest.Size(m)
}
func (m *PostAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountRequest proto.InternalMessageInfo

func (m *PostAccountRequest) GetData() *Account {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostAccountResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostAccountResponse) Reset()         { *m = PostAccountResponse{} }
func (m *PostAccountResponse) String() string { return proto.CompactTextString(m) }
func (*PostAccountResponse) ProtoMessage()    {}
func (*PostAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{21}
}

func (m *PostAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostAccountResponse.Unmarshal(m, b)
}
func (m *PostAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostAccountResponse.Marshal(b, m, deterministic)
}
func (m *PostAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostAccountResponse.Merge(m, src)
}
func (m *PostAccountResponse) XXX_Size() int {
	return xxx_messageInfo_PostAccountResponse.Size(m)
}
func (m *PostAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostAccountResponse proto.InternalMessageInfo

func (m *PostAccountResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PostContributionRequest struct {
	Data                 *Contribution `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PostContributionRequest) Reset()         { *m = PostContributionRequest{} }
func (m *PostContributionRequest) String() string { return proto.CompactTextString(m) }
func (*PostContributionRequest) ProtoMessage()    {}
func (*PostContributionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{22}
}

func (m *PostContributionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostContributionRequest.Unmarshal(m, b)
}
func (m *PostContributionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostContributionRequest.Marshal(b, m, deterministic)
}
func (m *PostContributionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostContributionRequest.Merge(m, src)
}
func (m *PostContributionRequest) XXX_Size() int {
	return xxx_messageInfo_PostContributionRequest.Size(m)
}
func (m *PostContributionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostContributionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostContributionRequest proto.InternalMessageInfo

func (m *PostContributionRequest) GetData() *Contribution {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostContributionResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostContributionResponse) Reset()         { *m = PostContributionResponse{} }
func (m *PostContributionResponse) String() string { return proto.CompactTextString(m) }
func (*PostContributionResponse) ProtoMessage()    {}
func (*PostContributionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{23}
}

func (m *PostContributionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostContributionResponse.Unmarshal(m, b)
}
func (m *PostContributionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostContributionResponse.Marshal(b, m, deterministic)
}
func (m *PostContributionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostContributionResponse.Merge(m, src)
}
func (m *PostContributionResponse) XXX_Size() int {
	return xxx_messageInfo_PostContributionResponse.Size(m)
}
func (m *PostContributionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostContributionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostContributionResponse proto.InternalMessageInfo

func (m *PostContributionResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PostGoalRequest struct {
	Data                 *Goal    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostGoalRequest) Reset()         { *m = PostGoalRequest{} }
func (m *PostGoalRequest) String() string { return proto.CompactTextString(m) }
func (*PostGoalRequest) ProtoMessage()    {}
func (*PostGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{24}
}

func (m *PostGoalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostGoalRequest.Unmarshal(m, b)
}
func (m *PostGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostGoalRequest.Marshal(b, m, deterministic)
}
func (m *PostGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostGoalRequest.Merge(m, src)
}
func (m *PostGoalRequest) XXX_Size() int {
	return xxx_messageInfo_PostGoalRequest.Size(m)
}
func (m *PostGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostGoalRequest proto.InternalMessageInfo

func (m *PostGoalRequest) GetData() *Goal {
	if m != nil {
		return m.Data
	}
	return nil
}

type PostGoalResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostGoalResponse) Reset()         { *m = PostGoalResponse{} }
func (m *PostGoalResponse) String() string { return proto.CompactTextString(m) }
func (*PostGoalResponse) ProtoMessage()    {}
func (*PostGoalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{25}
}

func (m *PostGoalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostGoalResponse.Unmarshal(m, b)
}
func (m *PostGoalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostGoalResponse.Marshal(b, m, deterministic)
}
func (m *PostGoalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostGoalResponse.Merge(m, src)
}
func (m *PostGoalResponse) XXX_Size() int {
	return xxx_messageInfo_PostGoalResponse.Size(m)
}
func (m *PostGoalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostGoalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostGoalResponse proto.InternalMessageInfo

func (m *PostGoalResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PostUserRequest struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostUserRequest) Reset()         { *m = PostUserRequest{} }
func (m *PostUserRequest) String() string { return proto.CompactTextString(m) }
func (*PostUserRequest) ProtoMessage()    {}
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{26}
}

func (m *PostUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostUserRequest.Unmarshal(m, b)
}
func (m *PostUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostUserRequest.Marshal(b, m, deterministic)
}
func (m *PostUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostUserRequest.Merge(m, src)
}
func (m *PostUserRequest) XXX_Size() int {
	return xxx_messageInfo_PostUserRequest.Size(m)
}
func (m *PostUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostUserRequest proto.InternalMessageInfo

func (m *PostUserRequest) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type User struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{27}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{28}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("financialplanningcalculator.Mode", Mode_name, Mode_value)
	proto.RegisterType((*Account)(nil), "financialplanningcalculator.Account")
	proto.RegisterType((*Contribution)(nil), "financialplanningcalculator.Contribution")
	proto.RegisterType((*Error)(nil), "financialplanningcalculator.Error")
	proto.RegisterType((*GetAccountsData)(nil), "financialplanningcalculator.GetAccountsData")
	proto.RegisterType((*GetAccountsRequest)(nil), "financialplanningcalculator.GetAccountsRequest")
	proto.RegisterType((*GetAccountsResponse)(nil), "financialplanningcalculator.GetAccountsResponse")
	proto.RegisterType((*GetCalculateData)(nil), "financialplanningcalculator.GetCalculateData")
	proto.RegisterType((*GetCalculateRequest)(nil), "financialplanningcalculator.GetCalculateRequest")
	proto.RegisterType((*GetCalculateResponse)(nil), "financialplanningcalculator.GetCalculateResponse")
	proto.RegisterType((*GetContributionData)(nil), "financialplanningcalculator.GetContributionData")
	proto.RegisterType((*GetContributionRequest)(nil), "financialplanningcalculator.GetContributionRequest")
	proto.RegisterType((*GetGoalData)(nil), "financialplanningcalculator.GetGoalData")
	proto.RegisterType((*GetGoalsRequest)(nil), "financialplanningcalculator.GetGoalsRequest")
	proto.RegisterType((*GetGoalsResponse)(nil), "financialplanningcalculator.GetGoalsResponse")
	proto.RegisterType((*GetHealthRequest)(nil), "financialplanningcalculator.GetHealthRequest")
	proto.RegisterType((*GetHealthRequest_DataMessage)(nil), "financialplanningcalculator.GetHealthRequest.DataMessage")
	proto.RegisterType((*GetHealthResponse)(nil), "financialplanningcalculator.GetHealthResponse")
	proto.RegisterType((*GetUserData)(nil), "financialplanningcalculator.GetUserData")
	proto.RegisterType((*GetUserRequest)(nil), "financialplanningcalculator.GetUserRequest")
	proto.RegisterType((*Goal)(nil), "financialplanningcalculator.Goal")
	proto.RegisterType((*Period)(nil), "financialplanningcalculator.Period")
	proto.RegisterType((*PostAccountRequest)(nil), "financialplanningcalculator.PostAccountRequest")
	proto.RegisterType((*PostAccountResponse)(nil), "financialplanningcalculator.PostAccountResponse")
	proto.RegisterType((*PostContributionRequest)(nil), "financialplanningcalculator.PostContributionRequest")
	proto.RegisterType((*PostContributionResponse)(nil), "financialplanningcalculator.PostContributionResponse")
	proto.RegisterType((*PostGoalRequest)(nil), "financialplanningcalculator.PostGoalRequest")
	proto.RegisterType((*PostGoalResponse)(nil), "financialplanningcalculator.PostGoalResponse")
	proto.RegisterType((*PostUserRequest)(nil), "financialplanningcalculator.PostUserRequest")
	proto.RegisterType((*User)(nil), "financialplanningcalculator.User")
	proto.RegisterType((*UserResponse)(nil), "financialplanningcalculator.UserResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 943 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xef, 0x6f, 0xdb, 0x44,
	0x18, 0x8e, 0x5d, 0xa7, 0x49, 0xde, 0x74, 0x6d, 0xb9, 0x4d, 0xc3, 0x2a, 0x68, 0x4a, 0xaf, 0x20,
	0xa5, 0xa3, 0x0d, 0x25, 0xa5, 0xe2, 0x87, 0x98, 0xb4, 0xb4, 0x09, 0x59, 0x84, 0x92, 0x56, 0x6e,
	0x36, 0x10, 0x48, 0x48, 0xb7, 0xf8, 0x18, 0xd6, 0x5c, 0x3b, 0xd8, 0xce, 0x24, 0x24, 0xbe, 0x20,
	0xf8, 0x9b, 0xf9, 0x8c, 0x7c, 0xbf, 0xe2, 0xcb, 0x32, 0xdb, 0x81, 0x6f, 0xbe, 0xcb, 0xfb, 0xbe,
	0xcf, 0xf3, 0xbc, 0x7e, 0xee, 0x3d, 0x07, 0xee, 0xc5, 0x34, 0x7a, 0xe3, 0xcd, 0x68, 0x67, 0x1e,
	0x85, 0x49, 0x88, 0x3e, 0xf8, 0xc5, 0x0b, 0x48, 0x30, 0xf3, 0x88, 0x3f, 0xf7, 0x49, 0x10, 0x78,
	0xc1, 0xab, 0x19, 0xf1, 0x67, 0x0b, 0x9f, 0x24, 0x61, 0x84, 0xff, 0x31, 0xa0, 0xd6, 0x9b, 0xcd,
	0xc2, 0x45, 0x90, 0xa0, 0xaf, 0xc1, 0xee, 0xb9, 0xee, 0x28, 0x48, 0x68, 0x44, 0xe3, 0x64, 0xf0,
	0x86, 0x46, 0xbf, 0x4f, 0x6e, 0x68, 0xe4, 0x85, 0x6e, 0x6c, 0x1b, 0x2d, 0xa3, 0xbd, 0xe5, 0xbc,
	0xf3, 0x77, 0x64, 0x43, 0xed, 0x92, 0xf8, 0x24, 0x98, 0x51, 0xdb, 0x6c, 0x19, 0x6d, 0xc3, 0x91,
	0x4b, 0xb4, 0x0b, 0xe6, 0xc8, 0xb5, 0xb7, 0x58, 0xbe, 0x39, 0x72, 0x11, 0x86, 0x1d, 0x59, 0xc2,
	0x21, 0x09, 0xb5, 0x2d, 0x16, 0xae, 0xed, 0xa1, 0x0b, 0xb0, 0xc6, 0xa1, 0x4b, 0xed, 0x6a, 0xcb,
	0x68, 0xef, 0x76, 0x0f, 0x3b, 0x39, 0x0a, 0x3a, 0x69, 0xa0, 0xc3, 0xc2, 0x11, 0x02, 0x6b, 0x42,
	0xee, 0xa8, 0xbd, 0xdd, 0x32, 0xda, 0x0d, 0x87, 0x3d, 0xa3, 0x87, 0xb0, 0xfd, 0x3c, 0xa6, 0xd1,
	0xc8, 0xb5, 0x6b, 0x8c, 0x82, 0x58, 0xe1, 0x29, 0xec, 0x5c, 0x85, 0x41, 0x12, 0x79, 0x2f, 0x17,
	0x89, 0x17, 0x06, 0xe8, 0x43, 0x68, 0x88, 0x3e, 0x8c, 0x5c, 0xa1, 0x76, 0xb9, 0x91, 0x56, 0xe9,
	0xdd, 0xa5, 0xcf, 0x42, 0x9d, 0x58, 0xad, 0x8a, 0xc3, 0x87, 0x50, 0x1d, 0x44, 0x51, 0x18, 0xa5,
	0xfd, 0x18, 0xd3, 0x38, 0x26, 0xaf, 0x28, 0x2b, 0xd6, 0x70, 0xe4, 0x12, 0x1f, 0xc3, 0xde, 0x90,
	0x26, 0xa2, 0x74, 0xdc, 0x27, 0x09, 0xc9, 0x70, 0x34, 0x34, 0x8e, 0x2f, 0x00, 0x65, 0x42, 0x1d,
	0xfa, 0xdb, 0x82, 0xc6, 0x09, 0x7a, 0x0a, 0x96, 0x4b, 0x12, 0xc2, 0x62, 0x9b, 0xdd, 0x93, 0xdc,
	0xe6, 0xac, 0x20, 0x39, 0x2c, 0x13, 0x7f, 0x0f, 0xf7, 0xb5, 0xba, 0xf1, 0x3c, 0x0c, 0x62, 0x8a,
	0x9e, 0x42, 0x5d, 0xee, 0xd9, 0x46, 0x6b, 0xab, 0xdd, 0xec, 0x7e, 0x94, 0x5b, 0x5c, 0x04, 0x3b,
	0x2a, 0x0b, 0xf7, 0x61, 0x7f, 0x48, 0x93, 0x2b, 0x11, 0x42, 0x99, 0x38, 0x1b, 0x6a, 0xba, 0x89,
	0xe4, 0x32, 0x23, 0xdb, 0xd4, 0x64, 0xff, 0xc0, 0xe8, 0xa9, 0x2a, 0x52, 0x77, 0x4f, 0xd3, 0x7d,
	0x5a, 0xa4, 0x5b, 0x63, 0x21, 0x84, 0x3f, 0x87, 0x07, 0x7a, 0x65, 0xa1, 0xfc, 0x49, 0x96, 0x63,
	0x2a, 0xfc, 0x28, 0xb7, 0x3a, 0x8f, 0x55, 0x42, 0xf0, 0x39, 0x27, 0x9c, 0xb1, 0x13, 0x53, 0x9e,
	0x6b, 0x29, 0xfc, 0x33, 0x3c, 0x5c, 0x49, 0x92, 0x42, 0xfb, 0x9a, 0xd0, 0xb3, 0x42, 0xa1, 0x2b,
	0xb8, 0x42, 0xeb, 0xc7, 0xd0, 0x1c, 0xd2, 0x64, 0x18, 0x12, 0x3f, 0xd7, 0x63, 0xd7, 0xcc, 0x8e,
	0x69, 0x98, 0x32, 0xd8, 0x37, 0x1a, 0x7e, 0xbb, 0x08, 0x5f, 0x42, 0x08, 0xdc, 0xef, 0x98, 0x07,
	0x44, 0x41, 0xd1, 0xdf, 0x2f, 0xa0, 0xca, 0x36, 0x44, 0x77, 0xf3, 0x0f, 0x74, 0x1a, 0xe9, 0xf0,
	0x78, 0x3c, 0x67, 0xc5, 0x9e, 0x51, 0xe2, 0x27, 0xbf, 0x4a, 0x7a, 0x63, 0x8d, 0xde, 0x57, 0x45,
	0xf4, 0xb4, 0xe4, 0x4e, 0x4a, 0x54, 0x9c, 0x44, 0xce, 0xf7, 0xe0, 0x1e, 0x34, 0x33, 0x9b, 0xf8,
	0x08, 0xde, 0xcb, 0x24, 0x09, 0xfe, 0xbb, 0x60, 0x5e, 0xbf, 0x66, 0x80, 0x75, 0xc7, 0xbc, 0x7e,
	0x8d, 0x8f, 0x58, 0x6f, 0xd3, 0x0e, 0xb2, 0xde, 0x3e, 0x80, 0xea, 0xe0, 0x8e, 0x78, 0xbe, 0x38,
	0xea, 0x7c, 0x81, 0x27, 0xb0, 0x2b, 0x82, 0xfe, 0x63, 0x63, 0x65, 0x7d, 0xd1, 0xd8, 0x3f, 0xc0,
	0x4a, 0x9b, 0x82, 0x1e, 0x01, 0x28, 0x17, 0xf1, 0x8e, 0x6e, 0x39, 0x99, 0x9d, 0x0d, 0x46, 0xb1,
	0x9c, 0x97, 0xd6, 0xda, 0x79, 0x59, 0xd5, 0x7c, 0xf2, 0x97, 0x01, 0xdb, 0xdc, 0xef, 0xff, 0x7f,
	0x4e, 0x2c, 0xfd, 0x60, 0x6e, 0xe8, 0x87, 0x09, 0xa0, 0x9b, 0x30, 0x96, 0xa3, 0x4b, 0xf6, 0xf5,
	0x4b, 0xad, 0xaf, 0xe5, 0xc8, 0xc8, 0x43, 0x72, 0x5f, 0xab, 0xb7, 0x7c, 0xdf, 0xea, 0xa0, 0x98,
	0x6c, 0x22, 0xbd, 0x9f, 0x86, 0xad, 0x3b, 0xac, 0x4f, 0x34, 0xec, 0xe3, 0x5c, 0x6c, 0x2d, 0x9f,
	0x13, 0x78, 0x0c, 0xf6, 0xdb, 0x95, 0xdf, 0xc1, 0xe2, 0x19, 0xec, 0xa5, 0xb1, 0xac, 0x1f, 0x02,
	0xfd, 0x42, 0x43, 0x2f, 0xd1, 0x47, 0x8e, 0x8a, 0x61, 0x7f, 0x59, 0x29, 0x1f, 0x2d, 0xeb, 0xdf,
	0x4d, 0xd0, 0x58, 0x1e, 0x47, 0x3b, 0x01, 0x2b, 0x5d, 0xad, 0x3f, 0x26, 0x02, 0xd7, 0x54, 0xb8,
	0x8f, 0x60, 0x87, 0x63, 0xae, 0xe7, 0xf5, 0xf8, 0x90, 0x7f, 0x1b, 0xa0, 0x3d, 0x68, 0x8e, 0x26,
	0x2f, 0x06, 0xb7, 0xd3, 0xf1, 0x60, 0x32, 0xbd, 0xdd, 0xaf, 0xa0, 0x3a, 0x58, 0xfd, 0xc1, 0xe5,
	0x74, 0xdf, 0xe8, 0xfe, 0xdd, 0x00, 0xfc, 0xad, 0xe4, 0x76, 0x23, 0xb8, 0x5d, 0x29, 0x6e, 0xb7,
	0xfc, 0xf3, 0x08, 0x45, 0xec, 0x14, 0x2b, 0x53, 0x7e, 0x5a, 0xf6, 0x26, 0x15, 0xed, 0x38, 0x38,
	0x2b, 0x9f, 0xc0, 0xb5, 0xe0, 0x0a, 0x5a, 0xc0, 0x4e, 0xf6, 0x06, 0x42, 0x67, 0xa5, 0xaf, 0x31,
	0x89, 0xfa, 0xd9, 0x06, 0x19, 0x0a, 0x36, 0x66, 0x53, 0x5e, 0xfb, 0xe0, 0x39, 0xdf, 0xe4, 0x5e,
	0x91, 0xe0, 0xe5, 0xfd, 0x8d, 0x2b, 0xc8, 0x83, 0xba, 0xbc, 0x09, 0xd0, 0x49, 0x99, 0x5b, 0x44,
	0x75, 0xf6, 0xb4, 0x64, 0xb4, 0xd2, 0xe7, 0x43, 0x43, 0x4d, 0x6d, 0x74, 0xba, 0xd1, 0x95, 0x70,
	0xd0, 0x29, 0x1b, 0xae, 0xd0, 0x7e, 0x82, 0x9a, 0x18, 0xcf, 0xe8, 0x93, 0x32, 0x43, 0x5c, 0x22,
	0x15, 0x9f, 0x18, 0x5c, 0x49, 0x5d, 0x99, 0x19, 0x49, 0x05, 0xae, 0x7c, 0x7b, 0x18, 0x16, 0xb8,
	0x72, 0xcd, 0xb4, 0xc3, 0x15, 0xf4, 0xa7, 0xc1, 0x07, 0x82, 0x66, 0x90, 0xcf, 0x0b, 0x0b, 0xad,
	0x73, 0xc8, 0xc5, 0x86, 0x59, 0x8a, 0x83, 0x07, 0x75, 0x39, 0x93, 0x0a, 0xdc, 0xb2, 0x32, 0x04,
	0x0b, 0xdc, 0xb2, 0x3a, 0xe8, 0x70, 0x05, 0x51, 0x0e, 0xc5, 0x5e, 0x60, 0x31, 0x54, 0xf6, 0x0d,
	0x1e, 0x17, 0xcf, 0x3c, 0x05, 0x73, 0xd9, 0xfc, 0xb1, 0xa1, 0xa2, 0x5f, 0x6e, 0xb3, 0x3f, 0x63,
	0xe7, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x9e, 0xbe, 0x84, 0x0e, 0x9d, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FinancialPlanningCalculatorServiceClient is the client API for FinancialPlanningCalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FinancialPlanningCalculatorServiceClient interface {
	// Get accounts
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error)
	// Get a calculation for the user.
	GetCalculate(ctx context.Context, in *GetCalculateRequest, opts ...grpc.CallOption) (*GetCalculateResponse, error)
	// Get an account contribution.
	GetContribution(ctx context.Context, in *GetContributionRequest, opts ...grpc.CallOption) (*Contribution, error)
	// Get all goals for a user.
	GetGoals(ctx context.Context, in *GetGoalsRequest, opts ...grpc.CallOption) (*GetGoalsResponse, error)
	// Health Check
	GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error)
	// Get a new user.
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	// Create an account.
	PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error)
	// Create an account contribution.
	PostContribution(ctx context.Context, in *PostContributionRequest, opts ...grpc.CallOption) (*PostContributionResponse, error)
	// Create a goal.
	PostGoal(ctx context.Context, in *PostGoalRequest, opts ...grpc.CallOption) (*PostGoalResponse, error)
	// Create a new user.
	PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type financialPlanningCalculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewFinancialPlanningCalculatorServiceClient(cc *grpc.ClientConn) FinancialPlanningCalculatorServiceClient {
	return &financialPlanningCalculatorServiceClient{cc}
}

func (c *financialPlanningCalculatorServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error) {
	out := new(GetAccountsResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) GetCalculate(ctx context.Context, in *GetCalculateRequest, opts ...grpc.CallOption) (*GetCalculateResponse, error) {
	out := new(GetCalculateResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetCalculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) GetContribution(ctx context.Context, in *GetContributionRequest, opts ...grpc.CallOption) (*Contribution, error) {
	out := new(Contribution)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) GetGoals(ctx context.Context, in *GetGoalsRequest, opts ...grpc.CallOption) (*GetGoalsResponse, error) {
	out := new(GetGoalsResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetGoals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) GetHealth(ctx context.Context, in *GetHealthRequest, opts ...grpc.CallOption) (*GetHealthResponse, error) {
	out := new(GetHealthResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetHealth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) PostAccount(ctx context.Context, in *PostAccountRequest, opts ...grpc.CallOption) (*PostAccountResponse, error) {
	out := new(PostAccountResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/PostAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) PostContribution(ctx context.Context, in *PostContributionRequest, opts ...grpc.CallOption) (*PostContributionResponse, error) {
	out := new(PostContributionResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/PostContribution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) PostGoal(ctx context.Context, in *PostGoalRequest, opts ...grpc.CallOption) (*PostGoalResponse, error) {
	out := new(PostGoalResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/PostGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialPlanningCalculatorServiceClient) PostUser(ctx context.Context, in *PostUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/PostUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialPlanningCalculatorServiceServer is the server API for FinancialPlanningCalculatorService service.
type FinancialPlanningCalculatorServiceServer interface {
	// Get accounts
	GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error)
	// Get a calculation for the user.
	GetCalculate(context.Context, *GetCalculateRequest) (*GetCalculateResponse, error)
	// Get an account contribution.
	GetContribution(context.Context, *GetContributionRequest) (*Contribution, error)
	// Get all goals for a user.
	GetGoals(context.Context, *GetGoalsRequest) (*GetGoalsResponse, error)
	// Health Check
	GetHealth(context.Context, *GetHealthRequest) (*GetHealthResponse, error)
	// Get a new user.
	GetUser(context.Context, *GetUserRequest) (*User, error)
	// Create an account.
	PostAccount(context.Context, *PostAccountRequest) (*PostAccountResponse, error)
	// Create an account contribution.
	PostContribution(context.Context, *PostContributionRequest) (*PostContributionResponse, error)
	// Create a goal.
	PostGoal(context.Context, *PostGoalRequest) (*PostGoalResponse, error)
	// Create a new user.
	PostUser(context.Context, *PostUserRequest) (*UserResponse, error)
}

// UnimplementedFinancialPlanningCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFinancialPlanningCalculatorServiceServer struct {
}

func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetAccounts(ctx context.Context, req *GetAccountsRequest) (*GetAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccounts not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetCalculate(ctx context.Context, req *GetCalculateRequest) (*GetCalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCalculate not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetContribution(ctx context.Context, req *GetContributionRequest) (*Contribution, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContribution not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetGoals(ctx context.Context, req *GetGoalsRequest) (*GetGoalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoals not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetHealth(ctx context.Context, req *GetHealthRequest) (*GetHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) PostAccount(ctx context.Context, req *PostAccountRequest) (*PostAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostAccount not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) PostContribution(ctx context.Context, req *PostContributionRequest) (*PostContributionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostContribution not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) PostGoal(ctx context.Context, req *PostGoalRequest) (*PostGoalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostGoal not implemented")
}
func (*UnimplementedFinancialPlanningCalculatorServiceServer) PostUser(ctx context.Context, req *PostUserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostUser not implemented")
}

func RegisterFinancialPlanningCalculatorServiceServer(s *grpc.Server, srv FinancialPlanningCalculatorServiceServer) {
	s.RegisterService(&_FinancialPlanningCalculatorService_serviceDesc, srv)
}

func _FinancialPlanningCalculatorService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_GetCalculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCalculateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetCalculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetCalculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetCalculate(ctx, req.(*GetCalculateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_GetContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetContribution(ctx, req.(*GetContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_GetGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetGoals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetGoals(ctx, req.(*GetGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetHealth(ctx, req.(*GetHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_PostAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).PostAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/PostAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).PostAccount(ctx, req.(*PostAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_PostContribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostContributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).PostContribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/PostContribution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).PostContribution(ctx, req.(*PostContributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_PostGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).PostGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/PostGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).PostGoal(ctx, req.(*PostGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialPlanningCalculatorService_PostUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).PostUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/PostUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).PostUser(ctx, req.(*PostUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FinancialPlanningCalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "financialplanningcalculator.FinancialPlanningCalculatorService",
	HandlerType: (*FinancialPlanningCalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccounts",
			Handler:    _FinancialPlanningCalculatorService_GetAccounts_Handler,
		},
		{
			MethodName: "GetCalculate",
			Handler:    _FinancialPlanningCalculatorService_GetCalculate_Handler,
		},
		{
			MethodName: "GetContribution",
			Handler:    _FinancialPlanningCalculatorService_GetContribution_Handler,
		},
		{
			MethodName: "GetGoals",
			Handler:    _FinancialPlanningCalculatorService_GetGoals_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _FinancialPlanningCalculatorService_GetHealth_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _FinancialPlanningCalculatorService_GetUser_Handler,
		},
		{
			MethodName: "PostAccount",
			Handler:    _FinancialPlanningCalculatorService_PostAccount_Handler,
		},
		{
			MethodName: "PostContribution",
			Handler:    _FinancialPlanningCalculatorService_PostContribution_Handler,
		},
		{
			MethodName: "PostGoal",
			Handler:    _FinancialPlanningCalculatorService_PostGoal_Handler,
		},
		{
			MethodName: "PostUser",
			Handler:    _FinancialPlanningCalculatorService_PostUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
