// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/service.proto

package financialplanningcalculator

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	AddInterestEveryNPeriods int64    `protobuf:"varint,1,opt,name=AddInterestEveryNPeriods,proto3" json:"AddInterestEveryNPeriods,omitempty"`
	Balance                  float32  `protobuf:"fixed32,2,opt,name=Balance,proto3" json:"Balance,omitempty"`
	InterestRate             float32  `protobuf:"fixed32,3,opt,name=InterestRate,proto3" json:"InterestRate,omitempty"`
	Mode                     string   `protobuf:"bytes,4,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Name                     string   `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe50f8fb92b2bd74, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAddInterestEveryNPeriods() int64 {
	if m != nil {
		return m.AddInterestEveryNPeriods
	}
	return 0
}

func (m *Account) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetInterestRate() float32 {
	if m != nil {
		return m.InterestRate
	}
	return 0
}

func (m *Account) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CalculateResponse struct {
	Periods              *Period  `protobuf:"bytes,1,opt,name=Periods,proto3" json:"Periods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculateResponse) Reset()         { *m = CalculateResponse{} }
func (m *CalculateResponse) String() string { return proto.CompactTextString(m) }
func (*CalculateResponse) ProtoMessage()    {}
func (*CalculateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe50f8fb92b2bd74, []int{1}
}

func (m *CalculateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculateResponse.Unmarshal(m, b)
}
func (m *CalculateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculateResponse.Marshal(b, m, deterministic)
}
func (m *CalculateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculateResponse.Merge(m, src)
}
func (m *CalculateResponse) XXX_Size() int {
	return xxx_messageInfo_CalculateResponse.Size(m)
}
func (m *CalculateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculateResponse proto.InternalMessageInfo

func (m *CalculateResponse) GetPeriods() *Period {
	if m != nil {
		return m.Periods
	}
	return nil
}

type Period struct {
	Accounts             *Account `protobuf:"bytes,1,opt,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Period) Reset()         { *m = Period{} }
func (m *Period) String() string { return proto.CompactTextString(m) }
func (*Period) ProtoMessage()    {}
func (*Period) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe50f8fb92b2bd74, []int{2}
}

func (m *Period) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Period.Unmarshal(m, b)
}
func (m *Period) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Period.Marshal(b, m, deterministic)
}
func (m *Period) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Period.Merge(m, src)
}
func (m *Period) XXX_Size() int {
	return xxx_messageInfo_Period.Size(m)
}
func (m *Period) XXX_DiscardUnknown() {
	xxx_messageInfo_Period.DiscardUnknown(m)
}

var xxx_messageInfo_Period proto.InternalMessageInfo

func (m *Period) GetAccounts() *Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "financialplanningcalculator.Account")
	proto.RegisterType((*CalculateResponse)(nil), "financialplanningcalculator.CalculateResponse")
	proto.RegisterType((*Period)(nil), "financialplanningcalculator.Period")
}

func init() { proto.RegisterFile("types/service.proto", fileDescriptor_fe50f8fb92b2bd74) }

var fileDescriptor_fe50f8fb92b2bd74 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0xb6, 0xb6, 0x3a, 0x7a, 0xd0, 0x08, 0x12, 0xda, 0x4b, 0x59, 0x3d, 0xf4, 0x94,
	0x42, 0xbd, 0x09, 0x82, 0xb5, 0x54, 0x51, 0xb0, 0x94, 0x88, 0x37, 0x2f, 0x69, 0x76, 0x5a, 0x16,
	0xd2, 0x64, 0x49, 0xd2, 0x42, 0xaf, 0xfe, 0x1d, 0xff, 0xa4, 0x74, 0xb3, 0x29, 0x8a, 0xd8, 0xdb,
	0x64, 0x32, 0xdf, 0x63, 0xe6, 0x3d, 0xb8, 0xf0, 0x9b, 0x02, 0x5d, 0xdf, 0xa1, 0x5d, 0xe7, 0x12,
	0x59, 0x61, 0x8d, 0x37, 0xa4, 0x33, 0xcf, 0xb5, 0xd0, 0x32, 0x17, 0xaa, 0x50, 0x42, 0xeb, 0x5c,
	0x2f, 0xa4, 0x50, 0x72, 0xa5, 0x84, 0x37, 0xb6, 0xdd, 0x59, 0x18, 0xb3, 0x50, 0xd8, 0x2f, 0x47,
	0x67, 0xab, 0x79, 0x1f, 0x97, 0x85, 0xdf, 0x04, 0x32, 0xfd, 0x4a, 0xa0, 0x35, 0x94, 0xd2, 0xac,
	0xb4, 0x27, 0xb7, 0x40, 0x87, 0x59, 0xf6, 0xac, 0x3d, 0x5a, 0x74, 0x7e, 0xbc, 0x46, 0xbb, 0x99,
	0x4c, 0xd1, 0xe6, 0x26, 0x73, 0x34, 0xe9, 0x26, 0xbd, 0x3a, 0xff, 0xf7, 0x9f, 0x50, 0x68, 0x3d,
	0x08, 0x25, 0xb4, 0x44, 0x5a, 0xeb, 0x26, 0xbd, 0x1a, 0x8f, 0x4f, 0x92, 0xc2, 0x69, 0x44, 0xb8,
	0xf0, 0x48, 0xeb, 0xe5, 0xf7, 0xaf, 0x1e, 0x21, 0xd0, 0x78, 0x35, 0x19, 0xd2, 0x46, 0x37, 0xe9,
	0x1d, 0xf3, 0xb2, 0xde, 0xf6, 0x26, 0x62, 0x89, 0xf4, 0x30, 0xf4, 0xb6, 0x75, 0xca, 0xe1, 0x7c,
	0x54, 0x1d, 0x86, 0x1c, 0x5d, 0x61, 0xb4, 0x43, 0x72, 0x07, 0xad, 0x9f, 0x5b, 0x9e, 0x0c, 0xae,
	0xd8, 0x1e, 0x3b, 0x58, 0x98, 0xe5, 0x91, 0x49, 0x5f, 0xa0, 0x19, 0x4a, 0x72, 0x0f, 0x47, 0x95,
	0x15, 0x51, 0xe9, 0x7a, 0xaf, 0x52, 0x35, 0xcc, 0x77, 0xd4, 0xe0, 0x33, 0x81, 0xf4, 0x31, 0x12,
	0xd3, 0x8a, 0x18, 0xed, 0x88, 0xb7, 0x10, 0x1a, 0xf9, 0x80, 0xb3, 0x27, 0xf4, 0xef, 0x0e, 0xed,
	0xee, 0x1a, 0x72, 0xc9, 0x42, 0x4c, 0x2c, 0xc6, 0xc4, 0xc6, 0xdb, 0x98, 0xda, 0x6c, 0xef, 0x0a,
	0x7f, 0xdc, 0x48, 0x0f, 0x66, 0xcd, 0x52, 0xe1, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x26, 0x6b,
	0xb8, 0xed, 0x2a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FinancialPlanningCalculatorServiceClient is the client API for FinancialPlanningCalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FinancialPlanningCalculatorServiceClient interface {
	// Calculate for the current user.
	GetUserCalculate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CalculateResponse, error)
}

type financialPlanningCalculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewFinancialPlanningCalculatorServiceClient(cc *grpc.ClientConn) FinancialPlanningCalculatorServiceClient {
	return &financialPlanningCalculatorServiceClient{cc}
}

func (c *financialPlanningCalculatorServiceClient) GetUserCalculate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*CalculateResponse, error) {
	out := new(CalculateResponse)
	err := c.cc.Invoke(ctx, "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUserCalculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialPlanningCalculatorServiceServer is the server API for FinancialPlanningCalculatorService service.
type FinancialPlanningCalculatorServiceServer interface {
	// Calculate for the current user.
	GetUserCalculate(context.Context, *empty.Empty) (*CalculateResponse, error)
}

// UnimplementedFinancialPlanningCalculatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFinancialPlanningCalculatorServiceServer struct {
}

func (*UnimplementedFinancialPlanningCalculatorServiceServer) GetUserCalculate(ctx context.Context, req *empty.Empty) (*CalculateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserCalculate not implemented")
}

func RegisterFinancialPlanningCalculatorServiceServer(s *grpc.Server, srv FinancialPlanningCalculatorServiceServer) {
	s.RegisterService(&_FinancialPlanningCalculatorService_serviceDesc, srv)
}

func _FinancialPlanningCalculatorService_GetUserCalculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUserCalculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/financialplanningcalculator.FinancialPlanningCalculatorService/GetUserCalculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialPlanningCalculatorServiceServer).GetUserCalculate(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FinancialPlanningCalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "financialplanningcalculator.FinancialPlanningCalculatorService",
	HandlerType: (*FinancialPlanningCalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserCalculate",
			Handler:    _FinancialPlanningCalculatorService_GetUserCalculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "types/service.proto",
}
