swagger: "2.0"
x-global-options:
  go_package: service
info:
  description: "Shows the trajectory of accounts in relation to goals."
  version: "0.0.0"
  title: "Financial Planning Calculator"
host: "localhost:3000"
basePath: "/svc/v1"
schemes:
- "https"
- "http"
paths:
  /user:
    post:
      description: Create a new user.
  /user/calculate:
    get:
      description: Calculate for the current user.
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/CalculateResponse"
definitions:
  CalculateResponse:
    type: object
    properties:
      Periods:
        $ref: '#/definitions/Periods'
  Periods:
    type: array
    items:
      $ref: '#/definitions/Period' 
  Period:
    type: object
    properties:
      Accounts:
        $ref: '#/definitions/Accounts'
  Accounts:
    type: array
    items:
        $ref: '#/definitions/Account'
  Account:
    type: object
    properties:
      Name:
        type: string
      Mode:
        type: string
        enum: ["debt", "investment"]
        description: "The mode determines how contributions work for the account. A debt account contribution will remove money from the balance. An investment account contribution will add money to the balance. This value also affects how interest is calculated."
      Balance:
        type: number
        format: double
        description: "The Balance of the account. 45.05"
      InterestRate:
        type: number
        format: double
        description: "The interest rate of hte account. %5.5 is 0.055."
      AddInterestEveryNPeriods:
        type: number
        format: int64
        description: "Not all accounts accrue interest at the same rate. Some may accrue interest once per year, once per month, etc. Since we use periods we need to know how many periods before interest is calculated. So, on a bi-weekly paycheck you might choose to view interest every 2 periods."
